on:
  push:
    paths:
      - '**/*.Rmd'

name: Render RMarkdown

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("tidyverse", "tidytuesdayR", "extrafont", "rmarkdown")'
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Render files
        run: |
          for changed_file in ${{ steps.files.outputs.all }} do
            if [ ${file: -4} == ".Rmd" ]
              Rscript -e 'rmarkdown::render("README.Rmd")'
            fi
          done
      - name: Commit results
        run: |
          git commit **/*.Rmd -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"